In [2]:
import tensorflow as tf
import numpy as np
#x是1个3行3列1深度的张量
x=tf.placeholder(tf.float32,(1,3,3,1))
# 2x2的掩码， 步长是（1,1,1,1)的valid平均值池化操作
sigma=tf.nn.avg_pool(x,(1,2,2,1),(1,1,1,1),'VALID')
#利用上述池化操作的结果， 构造一个函数F, 池化结果的和
F=tf.reduce_sum(sigma)
session=tf.Session()
#分别计算F在某一点xvalue处针对sigma和x的梯度
xvalue=np.random.randn(1,3,3,1)
grad=tf.gradients(F,[sigma,x])
results=session.run(grad,{x:xvalue})
#打印结果
print("----针对sigma的梯度----")
print(results[0])
print("----针对x的梯度----")
print(results[1])

----针对sigma的梯度----
[[[[1.]
   [1.]]

  [[1.]
   [1.]]]]
----针对x的梯度----
[[[[0.25]
   [0.5 ]
   [0.25]]

  [[0.5 ]
   [1.  ]
   [0.5 ]]

  [[0.25]
   [0.5 ]
   [0.25]]]]
