In [21]:
import tensorflow as tf
# 梯度下降的初始点
x=tf.Variable(tf.constant([[4],[3]],tf.float32), tf.float32)
w=tf.constant([[1,2]],tf.float32)
# 自己的函数
y=tf.reduce_sum(tf.matmul(w,tf.square(x)))

#梯度下降, 设置步长为0.25

# 标准的梯度下降法
#opti=tf.train.GradientDescentOptimizer(0.25).minimize(y)
# Adagrad梯度下降
#opti=tf.train.AdagradOptimizer(0.25,0.1).minimize(y)
# Momentum梯度下降法
#opti=tf.train.MomentumOptimizer(0.01,0.9).minimize(y)

# Nesterov梯度下降法
#opti=tf.train.MomentumOptimizer(0.01,0.9,use_nesterov=True).minimize(y)

# RMSProp梯度下降法
#opti=tf.train.RMSPropOptimizer(learning_rate=0.01, decay=0.9,epsilon=1e-10).minimize(y)

# 具备动量的RMSProp梯度下降法
#opti=tf.train.RMSPropOptimizer(learning_rate=0.01, decay=0.9,momentum=0.9,epsilon=1e-10).minimize(y)

# Adadelta法 
#opti=tf.train.AdadeltaOptimizer(learning_rate=0.01, rho=0.95,epsilon=1e-8).minimize(y)

# Adam法
opti=tf.train.AdamOptimizer(learning_rate=0.01, beta1=0.9, beta2=0.999,epsilon=1e-8).minimize(y)

#创建会话
session=tf.Session()
session.run(tf.global_variables_initializer())


#2次迭代
for i in range(3):
    session.run(opti)
    #打印每次迭代的值
    print('第%d次的迭代值'%(i+1))
    print(session.run(x))

第1次的迭代值
[[3.99]
 [2.99]]
第2次的迭代值
[[3.9800007]
 [2.980001 ]]
第3次的迭代值
[[3.9700027]
 [2.9700034]]
