In [3]:
import tensorflow as tf
import numpy as np
# 读取tfrecord文件列表, 这里只有一个trfrecord
records_queue = tf.train.string_input_producer(['data.tfrecord'], num_epochs=2)
#创建一个TFRecordReader对象
reader = tf.TFRecordReader()

_,serialized_example=reader.read(records_queue)
# 解析tfrecord中的数据, 每次只解析一个
features = tf.parse_single_example(
serialized_example,
features={
    'array_raw':tf.FixedLenFeature([],tf.string),
    'height': tf.FixedLenFeature([],tf.int64),
    'width': tf.FixedLenFeature([],tf.int64),
    'depth': tf.FixedLenFeature([],tf.int64)
})

# 解析出对应的值
array_raw = features['array_raw']
array = tf.decode_raw(array_raw, tf.float32) #解码
height=features['height']
width=features['width']
depth=features['depth']

# 创建会话
session = tf.Session()
session.run(tf.global_variables_initializer())
session.run(tf.local_variables_initializer())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=session, coord=coord)
# 循环5次解析文件流的数据
for i in range(5):
    ndarray,h,w,d = session.run([array, height, width, depth])
    ndarray = np.reshape(ndarray, [h,w,d])
    print('---第%(num)d次解析到的ndarray---'%{'num':i+1})
    print(ndarray)
    
coord.request_stop()
coord.join(threads)
session.close()

---第1次解析到的ndarray---
[[[1. 2. 1. 2.]
  [3. 4. 2. 9.]
  [5. 6. 0. 3.]]

 [[7. 8. 1. 6.]
  [9. 6. 1. 7.]
  [1. 2. 5. 9.]]]
---第2次解析到的ndarray---
[[[11. 12. 11.]
  [13. 14. 12.]
  [15. 16. 13.]]

 [[17. 18. 11.]
  [19. 10. 11.]
  [11. 12. 15.]]

 [[13. 14. 15.]
  [18. 11. 12.]
  [19. 14. 10.]]]
---第3次解析到的ndarray---
[[[21. 23. 21.]
  [23. 24. 22.]]

 [[27. 28. 24.]
  [29. 20. 21.]]]
---第4次解析到的ndarray---
[[[1. 2. 1. 2.]
  [3. 4. 2. 9.]
  [5. 6. 0. 3.]]

 [[7. 8. 1. 6.]
  [9. 6. 1. 7.]
  [1. 2. 5. 9.]]]
---第5次解析到的ndarray---
[[[11. 12. 11.]
  [13. 14. 12.]
  [15. 16. 13.]]

 [[17. 18. 11.]
  [19. 10. 11.]
  [11. 12. 15.]]

 [[13. 14. 15.]
  [18. 11. 12.]
  [19. 14. 10.]]]
