In [1]:
import tensorflow as tf

E:\ProgramData\Anaconda3_1\envs\tensorflow-1-5\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
E:\ProgramData\Anaconda3_1\envs\tensorflow-1-5\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
E:\ProgramData\Anaconda3_1\envs\tensorflow-1-5\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
E:\ProgramData\Anaconda3_1\envs\tensorfl

# 一维张量

In [5]:
t=tf.constant([1,2,3], tf.float32,name='t')
print(t)  # 只是打印了张量的一些信息

Tensor("t_3:0", shape=(3,), dtype=float32)


# Tensor转换为ndarray

## 一维张量

In [6]:
t = tf.constant([1,2,3] ,tf.float32)

### 创建会话

In [7]:
session=tf.Session()

In [8]:
### 张量转换为ndarray

array = session.run(t)

### 打印其数据结构类型及对应的值

In [12]:
print(type(array))

<class 'numpy.ndarray'>


In [13]:
print(array)

[1. 2. 3.]


### 也可以先创建会话,然后利用Tensor的成员函数eval,将Tensor转换为ndarray

In [15]:
session=tf.Session()
array = t.eval(session=session)
print(array)

[1. 2. 3.]


### 另一种写法

In [16]:
with tf.Session() as session:
    array = t.eval()
    print(array)

[1. 2. 3.]


# ndarray转换为Tensor

In [17]:
import numpy as np

In [18]:
# 一维的ndarray
array = np.array([1,2,3],np.float32)

In [19]:
# ndarray转换为tensor
t = tf.convert_to_tensor(array,tf.float32,name='t')
# 打印张量, 数据类型及其尺寸
print(t)

Tensor("t_4:0", shape=(3,), dtype=float32)


# 1,利用函数shape得到张量的尺寸

In [20]:
# 张量
t = tf.constant(
    [
        [1,2,3],
        [4,5,6]
    ],
    tf.float32
)
session=tf.Session()
# 张量的形状
s=tf.shape(t)
print('张量的形状:',session.run(s))

张量的形状: [2 3]


# 2利用函数get_shape或成员变量shape得到张量的尺寸

In [24]:
# 二维张量
t=tf.constant([
    [1,2,3],
    [4,5,6]
],tf.float32)

# 张量的尺寸
#s=t.shape
s=t.get_shape()
#打印s及其数据结构类型
print("s的值:", s)
print("s的数据结构类型:" ,type(s))
print("s[0]的值:", s[0])
print("s[0]的数据结构类型:",type(s[0]))
print("将s[0]的值转换为整数型:", s[0].value)
print(type(s[0].value))

s的值: (2, 3)
s的数据结构类型: <class 'tensorflow.python.framework.tensor_shape.TensorShape'>
s[0]的值: 2
s[0]的数据结构类型: <class 'tensorflow.python.framework.tensor_shape.Dimension'>
将s[0]的值转换为整数型: 2
<class 'int'>
