In [2]:
import tensorflow as tf
#卷积核
kernel=tf.constant([
    [[[3]] , [[4]]],
    [[[5]] , [[6]]]
],tf.float32)

#某一函数针F对sigma的导数
partial_sigma=tf.constant([
    [
        [[-1],[1],[3]],
        [[2],[-2],[-4]],
        [[-3],[4],[1]]
    ]
],tf.float32)

#针对未知张量的导数的反向计算
partial_x=tf.nn.conv2d_backprop_input((1,3,3,1) , kernel, partial_sigma, [1,1,1,1],'SAME')

#创建会话
session=tf.Session()
print(session.run(partial_x))

[[[[ -3.]
   [ -1.]
   [ 13.]]

  [[  1.]
   [  1.]
   [  1.]]

  [[  1.]
   [  2.]
   [-13.]]]]
