In [3]:
import tensorflow as tf
#二维张量
t=tf.constant([[1,2,3] ,[4,5,6]], tf.float32)
#水平镜像
rh=tf.reverse(t,axis=[0])
#垂直镜像
rv=tf.reverse(t,axis=[1])
#逆时针翻转180度, 先水平再垂直(或者先垂直再水平)
r=tf.reverse(t, axis=[0,1])
session=tf.Session()
print('水平镜像的结果:\n', session.run(rh))
print('垂直镜像的结果:\n', session.run(rv))
print('逆时针翻转180度的结果:\n', session.run(r))

水平镜像的结果:
 [[4. 5. 6.]
 [1. 2. 3.]]
垂直镜像的结果:
 [[3. 2. 1.]
 [6. 5. 4.]]
逆时针翻转180度的结果:
 [[6. 5. 4.]
 [3. 2. 1.]]
